-      - name: Terraform Init
-        run: terraform init
+      - name: Terraform Init
+        run: terraform init -input=false -lock-timeout=60s -no-color

       - name: Terraform Validate
         run: terraform validate
         working-directory: ./terraform

-      - name: Terraform Plan
-        run: terraform plan
+      - name: Terraform Plan
+        run: terraform plan -input=false -lock-timeout=60s -no-color -var="aws_access_key=${AWS_ACCESS_KEY_ID}" -var="aws_secret_key=${AWS_SECRET_ACCESS_KEY}"
         working-directory: ./terraform

-      - name: Terraform Apply (auto-approve)
-        if: github.ref == 'refs/heads/main'
-        run: terraform apply -auto-approve
+      - name: Terraform Apply (auto-approve)
+        if: github.ref == 'refs/heads/main'
+        run: terraform apply -input=false -auto-approve -var="aws_access_key=${AWS_ACCESS_KEY_ID}" -var="aws_secret_key=${AWS_SECRET_ACCESS_KEY}"
         working-directory: ./terraform
