name: Deploy IAM Policy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init -input=false -upgrade -backend-config="region=us-west-2"
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ./terraform

      - name: Terraform Plan (with debug)
        run: |
          terraform plan -input=false -lock-timeout=60s -no-color
        working-directory: ./terraform
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform-debug.log

      - name: Terraform Apply (auto-approve)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve -lock-timeout=60s
        working-directory: ./terraform
